### ISSUE TITLE
gem release?

### ISSUE THREAD

**Issue by sonots** [hata/embulk-encoder-commons-compress#1]
I want to use this plugin. Can you release a gem?

**Comment by hata** [comment]
Hi

Sorry for inconvenience.
I release the following gem.

embulk-encoder-commons-compress-0.1.0.gem

So, you can install the gem using the following command:

embulk gem install embulk-encoder-commons-compress

Please try it.

Thanks,
Hiroki

**Comment by sonots** [comment]
Thanks!

**Comment by hata** [comment]
No problem :)
